Repository epfl-SDP/android, pull requests merged in 2022-06, with the labels that each got.

#441 Work around `HomeActivity` failing test
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/androidx/AndroidXDataStoreFactoryTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/speech/android/AndroidSpeechRecognizerFactoryTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/HomeActivityTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/androidx/AndroidXDataStoreFactory.kt
Labels: update-me-please

#400 Text to speech feature
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/SpeechFacadeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/tts/android/AndroidTextToSpeechRecognizerTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/tts/android/FakeTextToSpeechFactory.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/ClassicChessBoardStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/Dsl.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/NavigationTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulArScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulContestScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulFollowingScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPlayScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPrepareGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulProfileScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulSettingsScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/authentication/AuthenticationScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/game/GameScreenTest.kt
  mobile/src/main/AndroidManifest.xml
  mobile/src/main/java/ch/epfl/sdp/mobile/application/speech/SpeechFacade.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/tts/TextToSpeech.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/tts/TextToSpeechFactory.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/tts/android/AndroidTextToSpeechFactory.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/HomeActivity.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulPuzzleGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/ActualGameScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/ActualPuzzleGameScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/delegating/DelegatingTextToSpeechState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/Graphics.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/GameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/GameScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/GameScreenTopBar.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/TextToSpeechState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/French.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/German.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/SwissGerman.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/puzzles/PuzzleGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/puzzles/PuzzleGameScreenState.kt
Labels: update-me-please

#451 Finalize missing translations
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/French.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/German.kt
Labels: update-me-please

#428 Set Gravity and Ellipsis for TextFields
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/authentication/AuthenticationScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/GameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/PromoteDialog.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/play/PlayScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/prepare_game/OpponentList.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/prepare_game/PrepareGameDialog.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/ProfileScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/puzzles/PuzzleGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/puzzles/PuzzleSelectionScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/EditLanguageDialog.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/EditProfileImageDialog.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/EditProfileNameDialog.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/social/FollowButton.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/social/SearchField.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/social/SocialScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/Badge.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/Contest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/ContestScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/CreateDialog.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/FiltersDialog.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/NextStepBanner.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/PoolCard.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/TournamentDetails.kt
Labels: update-me-please

#454 Fix chessboard numbers displayed with wrong `Density`
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/classic/ChessBoardModifiers.kt
Labels: bug

#455 Revert "Load puzzles via Flows (#450)"
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/ChessFacadeTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/ChessFacade.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/Puzzle.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulProfileScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulPuzzleGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulPuzzleSelectionScreen.kt
Labels: bug, update-me-please

#456 Strengthen en-passant rules constaints for puzzles
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/engine/rules/PawnRules.kt
Labels: bug, update-me-please

#457 Improve scrolling performance in `UserScreen`
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulSettingsScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulVisitedProfileScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/ProfileScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/ProfileTabBar.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/UserScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
Labels: update-me-please, performance
