Repository epfl-SDP/android, pull requests merged in 2022-05, with the labels that each got.

#283 Add Lichess puzzles parsers
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/chess/notation/AlgebraicNotationTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/chess/notation/FenNotationTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/chess/notation/FlowsTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/chess/notation/UciNotationTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/chess/parser/ParserTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/ChessFacade.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/notation/AlgebraicNotation.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/notation/AlgebraicNotationCombinators.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/notation/CommonNotationCombinators.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/notation/FenNotation.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/notation/FenNotationCombinators.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/notation/Flows.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/notation/UCINotation.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/notation/UCINotationCombinators.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/parser/Combinators.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulPlayScreen.kt
Labels: update-me-please

#277 Add support for nested fields in Firestore
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/DslNestingTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/RecordingDocumentEditScopeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/FakeDocumentRecord.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/FakeFieldMutation.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/query/FakeQuery.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/query/OrderByQueryDecorator.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/query/WhereFakeQueryDecorator.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/serialization/Records.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/firestore/FirestoreDocumentReferenceTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/firestore/FirestoreQueryTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/DocumentEditScope.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/FieldPath.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/Query.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/RecordingDocumentEditScope.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/firestore/FirestoreDocumentEditScope.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/firestore/FirestoreDocumentReference.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/firestore/FirestoreFieldPath.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/firestore/FirestoreFieldValue.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/firestore/FirestoreQuery.kt
Labels: update-me-please

#298 Add `PieceSubject` and `PieceBoardSubject`
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/chess/engine/truth/PieceBoardSubject.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/chess/engine/truth/PieceSubject.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/chess/notation/FenNotationTest.kt
Labels: update-me-please

#272 Edit profile image in Settings
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/AuthenticatedUserProfileScreenStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulEditProfileImageDialogTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulEditProfileNameDialogTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulSettingScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulSettingsScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/setting/SettingScreenTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/Profile.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulEditProfileImageDialog.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulSettingsScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/EditProfileImageDialog.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/EditProfileImageDialogState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/Emojis.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreenState.kt
Labels: update-me-please

#293 Extract `MatchChessBoardState` from `MatchGameScreenState`
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/ClassicChessBoardStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulArScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/game/MatchChessBoardStateTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefullArScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/MatchChessBoardState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/MatchGameScreenState.kt
Labels: update-me-please

#301 Use speech recognition from the game screen
  gradle/libs.versions.toml
  mobile/build.gradle.kts
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/SpeechFacadeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/speech/FailingSpeechRecognizerFactory.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/speech/SuccessfulSpeechRecognizerFactory.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/speech/SuspendingSpeechRecognizerFactory.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/speech/android/AndroidSpeechRecognizerFactoryTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/speech/android/AndroidSpeechRecognizerTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/speech/android/RecognitionListenerAdapterTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/AuthenticatedUserProfileScreenStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/ClassicChessBoardStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/CompositionLocalsTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/NavigationTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulArScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulEditProfileImageDialogTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulEditProfileNameDialogTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulFollowingScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPlayScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPrepareGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulProfileScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulSettingsScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/authentication/AuthenticationScreenTest.kt
  mobile/src/main/AndroidManifest.xml
  mobile/src/main/java/ch/epfl/sdp/mobile/application/speech/SpeechFacade.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/speech/SpeechRecognizer.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/speech/SpeechRecognizerFactory.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/speech/android/AndroidSpeechRecognizerFactory.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/speech/android/RecognitionListenerAdapter.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/CompositionLocals.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/HomeActivity.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/MatchGameScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/GameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/GameScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/SpeechRecognizerState.kt
Labels: update-me-please

#268 Speech recognizer output filtering
  mobile/src/main/java/ch/epfl/sdp/mobile/application/speech/ChessDictionary.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/speech/ChessSpeechDictionary.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/speech/ChessSpeechRecognitionFilter.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/speech/SpeechFilterRules.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/speech/SpeechRecognitionFilter.kt
  mobile/src/test/java/ch/epfl/sdp/mobile/test/application/speech/ChessSpeechRecognitionFilterTest.kt
Labels: update-me-please

#307 Add a `Badge` composable
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/tournaments/BadgeTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/Badge.kt
Labels: update-me-please

#316 Add the pool screens and associated states
  gradle/libs.versions.toml
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/tournaments/PoolCardTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/tournaments/TournamentsDetailsTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/Graphics.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingTabBar.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/DashedDivider.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/PoolCard.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/PoolTable.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/TournamentDetails.kt
Labels: update-me-please

#318 Add the tournament creation dialog
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/tournaments/CreateDialogTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/CreateDialog.kt
Labels: update-me-please

#326 Add the next step banner
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/tournaments/NextStepBannerTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/tournaments/TournamentsDetailsTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/Graphics.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/NextStepBanner.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/TournamentDetails.kt
Labels: update-me-please

#325 Add `Transaction` support to `FirestoreStore` and `FakeStore`
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/DslTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/FakeDocumentReference.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/FakeStore.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/FakeTransaction.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/firestore/FirestoreTransactionTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/Store.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/Transaction.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/firestore/FirestoreDocumentReference.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/firestore/FirestoreStore.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/firestore/FirestoreTransaction.kt
Labels: update-me-please

#327 Finish implementing the contest creation screen
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/tournaments/ContestScreenTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulContestsScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/Graphics.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/home/HomeScaffold.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/Contest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/ContestInfo.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/ContestScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/ContestScreenState.kt
  mobile/src/main/res/drawable/filtervariant.xml
  mobile/src/main/res/drawable/tournament_icon.xml
Labels: update-me-please

#300 Display clickable puzzle list from CSV file puzzles
  gradle/libs.versions.toml
  mobile/build.gradle.kts
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/ChessFacadeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/SocialFacadeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/chess/notation/FenNotationTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/assets/fake/FakeAssetManager.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/assets/fake/FakeAssetManagerTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/AuthenticatedUserProfileScreenStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/ClassicChessBoardStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/NavigationTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulArScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulEditProfileImageDialogTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulEditProfileNameDialogTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulFollowingScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPlayScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPrepareGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulProfileScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPuzzleSelectionScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulSettingsScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/authentication/AuthenticationScreenTest.kt
  mobile/src/main/assets/puzzles/puzzles.csv
  mobile/src/main/java/ch/epfl/sdp/mobile/application/Profile.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/StoreDocuments.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/authentication/AuthenticatedUser.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/ChessFacade.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/Puzzle.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/notation/FenNotationCombinators.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/assets/AssetManager.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/assets/android/AndroidAssetManager.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/HomeActivity.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulPuzzleGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulPuzzleSelectionScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulVisitedProfileScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/Graphics.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/home/HomeScaffold.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/puzzles/PuzzleGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/puzzles/PuzzleGameScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/puzzles/PuzzleInfo.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/puzzles/PuzzleSelectionScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/puzzles/PuzzleSelectionScreenState.kt
  mobile/src/main/res/drawable/puzzles.xml
Labels: update-me-please

#329 Add support for `DocumentSnapshot.get()`
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/FakeDocumentReference.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/firestore/FirestoreDocumentReferenceTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/DocumentReference.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/firestore/FirestoreDocumentReference.kt
Labels: update-me-please

#331 Introduce more delegation to the chessboard state implementation
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/ClassicChessBoardStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/game/MatchChessBoardStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/game/ChessBoardRobot.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/game/ChessBoardTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/game/GameScreenTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/notation/AlgebraicNotation.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulGameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefullArScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/AbstractMovableChessBoardState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/ActualChessBoardState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/ActualGameScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/MatchGameScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/core/GameDelegate.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/core/MatchGameDelegate.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/core/MutableGameDelegate.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/delegating/DelegatingChessBoardState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/delegating/DelegatingMovesInfoState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/delegating/DelegatingPlayersInfoState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/delegating/DelegatingPromotionMovableChessBoardState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/delegating/DelegatingPromotionState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/delegating/DelegatingSpeechRecognizerState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/GameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/GameScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/MovesInfoState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/PlayersInfoState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/PromoteDialog.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/SpeechRecognizerState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/classic/ChessBoardModifiers.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/classic/ClassicChessBoard.kt
Labels: update-me-please

#336 Add State to CreateTournament Dialog
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/TournamentFacadeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulCreateTournamentScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/tournaments/TournamentFacade.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulContestsScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulCreateTournamentScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/CreateDialog.kt
Labels: update-me-please

#337 Add a stateful screen for tournaments
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/Dsl.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/TournamentFacadeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/Dsl.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/tournaments/StatefulTournamentDetailsScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/tournaments/TournamentsDetailsTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/StoreDocuments.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/tournaments/Tournament.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/tournaments/TournamentFacade.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulCreateTournamentScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/tournaments/ActualTournamentDetailsState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/tournaments/StatefulTournamentDetailsScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/tournaments/TournamentDetailsActions.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/TournamentDetails.kt
Labels: update-me-please

#342 Fix bottom navigation labels ellipsis
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/home/HomeScaffold.kt
Labels: bug

#355 Sprint 6 Summary
  wiki/Sprint-6.txt
Labels: update-me-please

#379 Rename `Sprint-6.txt` to `Sprint-6.md`
  wiki/Sprint-6.md
Labels: update-me-please

#380 Add some confetti when the player wins a match or a puzzle
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/Assertions.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/game/ConfettiTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/Confetti.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/GameScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/puzzles/PuzzleGameScreen.kt
Labels: update-me-please

#384 Remove unnecessary non-null assertion (!!) on a non-null receiver
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/voice/VoiceInputCombinator.kt
Labels: update-me-please

#386 Temporarily disable AR screen test
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulArScreenTest.kt
Labels: bug, update-me-please

#382 Add/Refactor icons to be faithful to Figma mockups
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulPuzzleSelectionScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/Graphics.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/authentication/AuthenticationScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/home/HomeScaffold.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
  mobile/src/main/res/drawable/ic_edit.xml
  mobile/src/main/res/drawable/ic_filter.xml
  mobile/src/main/res/drawable/ic_local_play.xml
  mobile/src/main/res/drawable/ic_logos_authentication.xml
  mobile/src/main/res/drawable/ic_online_play.xml
  mobile/src/main/res/drawable/ic_tab_icons_friends_filled.xml
  mobile/src/main/res/drawable/ic_tab_icons_friends_hollow.xml
  mobile/src/main/res/drawable/ic_tab_icons_play_filled.xml
  mobile/src/main/res/drawable/ic_tab_icons_play_hollow.xml
  mobile/src/main/res/drawable/ic_tab_icons_puzzles_filled.xml
  mobile/src/main/res/drawable/ic_tab_icons_puzzles_hollow.xml
  mobile/src/main/res/drawable/ic_tab_icons_settings_filled.xml
  mobile/src/main/res/drawable/ic_tab_icons_settings_hollow.xml
  mobile/src/main/res/drawable/ic_tab_icons_tournaments_filled.xml
  mobile/src/main/res/drawable/ic_tab_icons_tournaments_hollow.xml
Labels: update-me-please

#385 Use `setContentWithTestEnvironment` in existing tests
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/AuthenticatedUserProfileScreenStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/NavigationTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulCreateTournamentScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulEditProfileImageDialogTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulEditProfileNameDialogTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulFollowingScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPrepareGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPuzzleGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPuzzleSelectionScreenTest.kt
Labels: update-me-please

#378 Optimize `Query.get()` to avoid `asFlow()` usage
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/FakeCollectionReference.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/query/AbstractFakeQuery.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/query/FakeQuery.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/query/LimitFakeQueryDecorator.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/query/OrderByQueryDecorator.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/fake/query/WhereFakeQueryDecorator.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/store/firestore/FirestoreQueryTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/Query.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/store/firestore/FirestoreQuery.kt
Labels: update-me-please

#388 Show the checkmate position when a king is checkmate
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/delegating/DelegatingChessBoardState.kt
Labels: update-me-please

#383 Add support for AndroidX DataStore
  gradle/libs.versions.toml
  mobile/build.gradle.kts
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/Dsl.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/DslTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/androidx/AndroidXDataStoreFactoryTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/androidx/AndroidXKeyFactoryTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/androidx/AndroidXMutablePreferencesTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/androidx/AndroidXPreferencesDataStoreTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/androidx/AndroidXPreferencesTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/fake/FakeDataStoreFactory.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/fake/FakeKey.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/fake/FakeKeyFactory.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/fake/FakeMutablePreferences.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/fake/FakePreferences.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/fake/FakePreferencesDataStore.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/DataStore.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/DataStoreFactory.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/Edit.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/Key.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/KeyFactory.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/MutablePreferences.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/Preferences.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/androidx/AndroidXDataStoreFactory.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/androidx/AndroidXKey.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/androidx/AndroidXKeyFactory.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/androidx/AndroidXMutablePreferences.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/androidx/AndroidXPreferences.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/persistence/datastore/androidx/AndroidXPreferencesDataStore.kt
Labels: update-me-please

#389 implement un/following button on the profile screen
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulProfileScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/profile/VisitedProfileScreenTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulVisitedProfileScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/ProfileScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/VisitedProfileScreenState.kt
Labels: update-me-please

#356 Logout button
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulSettingsScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/setting/SettingScreenTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulSettingsScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/Graphics.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreenState.kt
Labels: update-me-please

#390 Display solved puzzles in profile/settings screen
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/assets/fake/FakeAssetManager.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/AuthenticatedUserProfileScreenStateTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/Dsl.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulProfileScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulSettingsScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/tournaments/StatefulTournamentDetailsScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/profile/UserScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/profile/VisitedProfileScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/setting/SettingScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/setting/SettingTabBarTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulProfileScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulSettingsScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulVisitedProfileScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/core/PuzzleGameDelegate.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/ProfileScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/ProfileScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/ProfileTabBar.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/UserScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/VisitedProfileScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreenState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/TournamentDetails.kt
Labels: update-me-please

#398 Rotate the board for the black player
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPuzzleGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/game/ChessBoardRobot+PlayDsl.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/game/ChessBoardRobot.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/game/ChessBoardTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/delegating/DelegatingPromotionMovableChessBoardState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/game/delegating/DelegatingPuzzlePromotionMovableChessBoardState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/MovableChessBoardState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/classic/ChessBoardModifiers.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/classic/ClassicChessBoard.kt
Labels: update-me-please

#403 Add a comment to `PersistentBoard`
  mobile/src/main/java/ch/epfl/sdp/mobile/application/chess/engine/implementation/PersistentBoard.kt
Labels: update-me-please

#399 Implement tournaments filtering
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/TournamentFacadeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/Dsl.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/NavigationTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulArScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulContestScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPlayScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPrepareGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulProfileScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulSettingsScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/tournaments/StatefulFiltersDialogScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/authentication/AuthenticationScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/tournaments/FiltersDialogTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/tournaments/TournamentFacade.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/HomeActivity.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulContestsScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/tournaments/StatefulFiltersDialogScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/LocalizedStrings.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/FiltersDialog.kt
Labels: update-me-please

#411 Fix incorrect package for `TimeProvider`
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/TournamentFacadeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/tournaments/TournamentTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/time/fake/FakeTimeProvider.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/Dsl.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/NavigationTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulArScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulContestScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulHomeTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPlayScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulPrepareGameScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulProfileScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/StatefulSettingsScreenTest.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/authentication/AuthenticationScreenTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/tournaments/StoreDocumentTournament.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/tournaments/Tournament.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/tournaments/TournamentFacade.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/time/TimeProvider.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/infrastructure/time/system/SystemTimeProvider.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/HomeActivity.kt
Labels: update-me-please

#410 Remove the visible divider and improve indicator behaviour on scroll
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/ContestScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/TournamentDetails.kt
Labels: update-me-please, design

#391 Refactor AR Screen to not destroy all pieces' node
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/game/ar/ChessSceneTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefullArScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/ar/ArChessBoardScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/game/ar/ChessScene.kt
Labels: AR

#404 Add a description of the principal packages
  README.md
Labels: documentation, update-me-please

#418 Fix `FakeDataStoreFactory`
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/Dsl.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/infrastructure/persistence/datastore/fake/FakeDataStoreFactory.kt
Labels: bug

#392 Tournaments refactor
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/Dsl.kt
  mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/tournaments/StatefulTournamentDetailsScreenTest.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/tournaments/StoreDocumentTournament.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/tournaments/Tournament.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/application/tournaments/TournamentFacade.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulContestsScreen.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/state/tournaments/ActualTournamentDetailsState.kt
  mobile/src/main/java/ch/epfl/sdp/mobile/ui/i18n/English.kt
Labels: update-me-please

#426 Apply localized strings in the right order
  mobile/src/main/java/ch/epfl/sdp/mobile/state/HomeActivity.kt
Labels: bug
